[package]
name = "benches"
version = "0.0.0"
publish = false
edition = "2018"

[dev-dependencies]
fireworks = { version = "*", path = "../fireworks" }
criterion = "*"

[[bench]]
name = "main_benchmarks"
path = "main_benchmarks.rs"
harness = false
